-- noinspection SqlNoDataSourceInspectionForFile

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS film_mpa CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS film_genre CASCADE;
DROP TABLE IF EXISTS likes CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar UNIQUE NOT NULL,
    login    varchar UNIQUE NOT NULL,
    name     varchar,
    birthday date
);

CREATE TABLE IF NOT EXISTS film_mpa
(
    mpa_id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name        varchar NOT NULL,
    mpa_description varchar
);

create TABLE IF NOT EXISTS films
(
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar UNIQUE NOT NULL,
    description  varchar        NOT NULL,
    release_date date,
    duration     integer,
    mpa_id       integer,
    FOREIGN KEY (mpa_id) REFERENCES film_mpa (mpa_id) ON delete SET NULL
);

CREATE TABLE IF NOT EXISTS friends
(
    user_id   integer NOT NULL,
    friend_id integer NOT NULL,
    PRIMARY KEY (friend_id, user_id)
);

CREATE TABLE IF NOT EXISTS genre
(
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);

create TABLE IF NOT EXISTS film_genre
(
    film_id  integer REFERENCES films (id) ON delete CASCADE,
    genre_id integer REFERENCES genre (id) ON delete CASCADE,
    PRIMARY KEY (film_id, genre_id)
);

create TABLE IF NOT EXISTS likes
(
    film_id integer NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (film_id, user_id)
);